apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo
spec:
  requestedFreight:
  - origin:
      kind: Stage
      name: qa
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/rajaramiotfal/multi-cluster-gitops.git
      writeBranch: main
      kustomize:
        images:
        - image: docker.io/rajarammurali513/demoapp
          path: envs/prod
