apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: qa
  namespace: demoapp
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: demoapp-qa
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/rajaramiotfal/multi-cluster-gitops-structure.git
          checkout:
            branch: main
      - uses: kustomize-set-image
        config:
          path: envs/qa
          images:
          - name: docker.io/rajarammurali513/demoapp
      - uses: git-commit
        config:
          message: "Promote image to QA"
      - uses: git-push
